### ISSUE TITLE
Enable presubmit alerting for circular references.

### ISSUE THREAD

**Issue by polina-c** [polina-c/layerlens#4]
There should be parameter that causes layerlens to fail if there are circular dependencies between libraries:

```
dart run layerlens --fail-on-circles
```

Adding this command to presubmit validation bot will ensure the library is circle-free.

If you want this to be implemented, upvote this issue and explain why you want it.

**Comment by martingeorgiu** [comment]
We would love this feature as it would enable us to use this package easily in our workflows triggered on PR:)

**Comment by polina-c** [comment]
Great! Will do nearest time!

**Comment by sigurdm** [comment]
Nit: probably you want to call it: `--fail-on-cycles` :)

**Comment by polina-c** [comment]
PR: https://github.com/polina-c/layerlens/pull/17

**Comment by polina-c** [comment]
@martingeorgiu , @jpoh281, @mzdm, let me know how the alerting worked for you

**Comment by mzdm** [comment]
> @martingeorgiu , @jpoh281, @mzdm, let me know how the alerting worked for you

Will take some time until we get rid off of all inversions. But will let you know 👍

**Comment by polina-c** [comment]
@mzdm , if you want flag like `--fail-if-cycles-more-than 25` to track progress, feel free to create issue.
